version: '3'
services:
  phishingalert:
    restart: always
    env_file: .env
    build: .
    ports:
      - "5000:5000"
    networks:
      - db_network
      - web_network
  mongo:
    restart: always
    env_file: .env
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - db_network
  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - phishingalert
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge