version: '3'
services:
  tornado:
    restart: always
    build: .
    ports:
      - "5000:5000"
    networks:
      - db_network
      - web_network
      - mq_network
  ml:
    restart: always
    build: ml
    ports:
    - "43000:43000"
    networks:
      - mq_network
  domain_processor:
    restart: always
    build: domain_processor
    ports:
    - "43001:43001"
    environment:
      - PRODUCTION=1
    networks:
      - mq_network
      - db_network
  mongo:
    restart: always
    env_file: .env
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - db_network
  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - tornado
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
  mq_network:
    driver: bridge